#' Get min. exams
#'
#' Returns dataframe reduced to one line per Reader ("Name") with
#' minimum value in column "min_exams" (requires those two column names).
#'
#' @param df data.frame as generated by "divide" core functions
#'
#' @importFrom dplyr %>% group_by slice ungroup
#'
#' @export
slice_min_exams <- function(df) {
  df %>%
    group_by(Name) %>%
    slice(which.min(min_exams)) %>%
    ungroup()
}


#' force_rbind helper function
#'
#' Bind_rows of 2 data frames regardless of NA or NULL in first arg.
#' Is used to assign cases to nested dataframe when reader
#' has no cases yet.
#'
#' @param x,y Data frames; x can be NULL or NA.
#'
#' @importFrom dplyr bind_rows
#'
#' @export

force_rbind <- function(x, y) {
  if (is.null(x) | all(is.na(x))) {
    x <- y
  } else {
    x <- dplyr::bind_rows(x, y)
  }
}

#' ignyt kable
#'
#' Fancy Rmd table styling
#'
#' @param x Data frame
#'
#' @importFrom knitr kable
#' @importFrom kableExtra kable_styling
#'
#' @export

ignyt_kable <- function(x) {
  x %>%
    knitr::kable() %>%
    kableExtra::kable_styling(
      bootstrap_options = c("striped", "hover", "condensed", "responsive")
    )
}
